// ? data of items stored in an object in data array..........
let data = [{
    id: "a",
    name: "God of Mischief",
    price: 1499,
    img: "Images/loki.webp",
    description: "Loki - A Cunning master of Chaos & Deception."
}, 
{
    id: "b",
    name: "Berserking Menace",
    price: 1499,
    img: "Images/ashura.webp",
    description: "Anime Oversized T-shirt",
},
{
    id: "c",
    name: "N - Horror",
    price: 1499,
    img: "Images/ashura1.webp",
    description: "Heavy Patch Worked Washed T-shirt",
}, 
{
    id: "d",
    name: "Anti-Magic",
    price: 1499,
    img: "Images/ashura2.webp",
    description: "Doc Sleeves Washed T-shirt",
},
{
    id: "e",
    name: "Ashura",
    price: 1499,
    img: "Images/ashura3.webp",
    description: "Ashura - Symbol of Grief, Valor And Tragedy",
}, 
{
    id: "f",
    name: "God - Complex",
    price: 1499,
    img: "Images/ashura4.webp",
    description: "Doc Sleeves Washed T-shirt"
},
{
    id: "g",
    name: "Alchemy",
    price: 1499,
    img: "Images/ashura5.webp",
    description: "Washed T-shirt",
}, 
{
    id: "h",
    name: "Finish-Your-Work",
    price: 1499,
    img: "Images/ashura6.webp",
    description: "Anime Oversized T-shirt With Patch Work",
},
{
    id: "i",
    name: "Kaiju V1",
    price: 1499,
    img: "Images/ashura7.webp",
    description: "Anime Oversized T-shirt",
}, 
{
    id: "j",
    name: "Weapon NO. 10",
    price: 1499,
    img: "Images/ashura8.webp",
    description: "Fully Armoured T-shirt",
},
{
    id: "k",
    name: "Centebrae",
    price: 1499,
    img: "Images/ashura9.webp",
    description: "Cut N Stitched Washed T-shirt",
}, 
{
    id: "l",
    name: "Paradise",
    price: 1499,
    img: "Images/ashura10.webp",
    description: "Paradise Convertible T-shirt",
},
{
    id: "m",
    name: "Nerv 01",
    price: 1499,
    img: "Images/ashura11.webp",
    description: "Acid washed V2-Anime Oversized T-shirt",
}, 
{
    id: "n",
    name: "Pillar of Stone",
    price: 1499,
    img: "Images/ashura12.webp",
    description: "Anime Oversized T-shirt With Patch Work",
},
{
    id: "o",
    name: "Freedom",
    price: 1499,
    img: "Images/ashura13.webp",
    description: "Acid Washed - AOT Anime Oversized T-shirt",
},
{
    id: "p",
    name: "Weakest Hunter",
    price: 1499,
    img: "Images/ashura14.webp",
    description: "Anime Oversized T-shirt With Contrast Stitch",
}, 

]